name: TEST
run-name: ${{github.actor}} is testing your projects' units.
on:
  push:
    branches:
      - main

env:
  NODE_ENV: TEST
  POSTGRES_DATABASE_URL: ""
  ORM_STRATEGY: drizzle
  DATABASE_STRATEGY: postgres

jobs:
  test_units:
    name: Testing Project Units
    runs-on: ubuntu-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Run unit test
        run: npm run test

